export const tourLanguages = [
  { language: 'Amharic' },
  { language: 'Arabic' },
  { language: 'Basque' },
  { language: 'Bengali' },
  { language: 'English (UK)' },
  { language: 'Portuguese (Brazil)' },
  { language: 'Bulgarian' },
  { language: 'Catalan' },
  { language: 'Cherokee' },
  { language: 'Croatian' },
  { language: 'Czech' },
  { language: 'Danish' },
  { language: 'Dutch' },
  { language: 'English (US)' },
  { language: 'Estonian' },
  { language: 'Filipino' },
  { language: 'Finnish' },
  { language: 'French' },
  { language: 'German' },
  { language: 'Greek' },
  { language: 'Gujarati' },
  { language: 'Hebrew' },
  { language: 'Hindi' },
  { language: 'Hungarian' },
  { language: 'Icelandic' },
  { language: 'Indonesian' },
  { language: 'Italian' },
  { language: 'Japanese' },
  { language: 'Kannada' },
  { language: 'Korean' },
  { language: 'Latvian' },
  { language: 'Lithuanian' },
  { language: 'Malay' },
  { language: 'Malayalam' },
  { language: 'Marathi' },
  { language: 'Norwegian' },
  { language: 'Polish' },
  { language: 'Portuguese (Portugal)' },
  { language: 'Romanian' },
  { language: 'Russian' },
  { language: 'Serbian' },
  { language: 'Chinese (PRC)' },
  { language: 'Slovak' },
  { language: 'Slovenian' },
  { language: 'Spanish' },
  { language: 'Swahili' },
  { language: 'Swedish' },
  { language: 'Tamil' },
  { language: 'Telugu' },
  { language: 'Thai' },
  { language: 'Chinese (Taiwan)' },
  { language: 'Turkish' },
  { language: 'Urdu' },
  { language: 'Ukrainian' },
  { language: 'Vietnamese' },
  { language: 'Welsh' },
];
